version: '3.8'

services:
  backend:
    build: .
    container_name: smart-hospital-backend
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
